version: 1.1.{build}
image: Visual Studio 2019
skip_commits:
  files:
    - README.md
    - **/*.txt'
dotnet_csproj:
  patch: true
  file: '**\*.csproj'
  version: '{version}'
  version_prefix: '{version}'
  package_version: '{version}'
  file_version: '{version}'
  informational_version: '{version}'
before_build:
- pwsh: nuget restore src/Rhyous.Odata.sln
build:
  project: src/Rhyous.Odata.sln
  verbosity: minimal
test:
  categories:
    except:
    - slow
artifacts:
  - path: '**\*.nupkg'
deploy:
- provider: NuGet
  api_key:
    secure: YuESu/nQz4WK2RIjra4BXLJ7dDNM/7mJcKJAJQZCiYlKgMBPozzyCSRIBgu/72mC