<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFrameworks>netstandard2.0</TargetFrameworks>
    <Authors>Jared Barneck (Rhyous)</Authors>
    <Company>Rhyous Publishing LLC</Company>
    <Version>1.3.0</Version>
    <AssemblyVersion>1.3.0.0</AssemblyVersion>
    <FileVersion>1.3.0.0</FileVersion>
    <Copyright>Copyright Jared Barneck (Rhyous) 2017</Copyright>
    <PackageLicenseFile>License.txt</PackageLicenseFile>
    <Description>A library to aid in providing csdl format for a given type.</Description>
    <PackageTags>csdl</PackageTags>
    <PackageProjectUrl>https://github.com/rhyous/Odata</PackageProjectUrl>
    <RepositoryUrl>https://github.com/rhyous/Odata</RepositoryUrl>
    <RepositoryType>Git</RepositoryType>
    <GeneratePackageOnBuild>true</GeneratePackageOnBuild>
    <PackageReadmeFile>README.md</PackageReadmeFile>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="System.ComponentModel.Annotations" Version="5.0.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Rhyous.Odata\Rhyous.Odata.csproj" />
  </ItemGroup>

  <ItemGroup>
    <None Include="..\..\License.txt">
      <Pack>True</Pack>
      <PackagePath></PackagePath>
    </None>
    <None Include="README.md">
      <Pack>True</Pack>
      <PackagePath>\</PackagePath>
    </None>
  </ItemGroup>

</Project>
